config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users
  resources :users, only:[:show]
  resources :posts do
    resources :likes
    resources :comments
  end
  delete 'delete_image/:id' => 'posts#delete_image', as: 'delete_image'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :images, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    private

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
    end

    def after_sign_in_path_for(resource)
        current_user
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, except: [:index]
    before_action :find_post!

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_back(fallback_location: root_path)
    end

    def show
        @comment = Comment.find(params[:id])
    end

    private

    def find_post!
        @post = Post.find_by_slug!(params[:post_slug])
    end

    def comment_params
        params.require(:comment).permit(:body)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_post
    before_action :find_like, only: [:destroy]

    def create
        if already_liked?
            flash[:notice] = "You can't like more than once"
        else
            @post.likes.create(user_id: current_user.id)
        end
        redirect_back(fallback_location: request.referer)
    end

    def destroy
        if !(already_liked?)
            flash[:notice] = "Cannot unlike"
        else
            @like.destroy
        end
        redirect_back(fallback_location: request.referer)
    end

    private

    def already_liked?
        Like.where(user_id: current_user.id, post_id:params[:post_id]).exists?
    end

    def find_like
        @like = @post.likes.find(params[:id])
    end

    def find_post
        @post = Post.find(params[:post_id])
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        if @post.save
            redirect_to @post
        else
            render 'new'
        end
    end

    def index
        @posts = Post.all
    end

    def show
    end

    def new
        @post = Post.new
    end

    def edit
    end

    def update
        respond_to do |format|
            if @user.update(user_params)
                format.html { redirect_to @user, notice: 'User was successfully updated.' }
                format.json { render :show, status: :ok, location: @user }
            else
                format.html { render :edit }
                format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @post.destroy

        redirect_to root_path
    end

    def delete_image
        @images = ActiveStorage::Attachment.find(params[:id])
        @images.purge

        redirect_back(fallback_location: request.referer)
    end

    private

    def set_post
        @post = Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:user_id, images: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def home
        if !user_signed_in?
            redirect_to new_user_session_path
        else
            redirect_to users_path
        end
    end

    def show
        @user = User.find(params[:id])
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comments.html.erb
<p>
    <%= @post.comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: comment, url: post_comments_path(:post) do |f| %>
    <div>
        <%= f.hidden_field :user_id, value: current_user.id %>
        Text: <%= f.text_area :body %>
    </div>
    <div>
        <%= f.submit %>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-dark bg-dark navbar-expand-md">
    <div class="container">
        <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            &#x2630;
        </button>
        <%= link_to 'Instagram', root_path, class: 'navbar-brand' %>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
            </ul>
            <div class="navbar-nav ml-auto">
                <div class="navbar-nav ml-auto">
                    <% if user_signed_in? %>
                        <div class="nav-item">
                            <span class="navbar-text">
                                Hello, &nbsp;
                            <span>
                        </div>
                        <div class="dropdown show">
                            <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'btn btn-secondary dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <%= link_to 'Мой профайл', current_user, class: 'dropdown-item' %>
                                <%= link_to 'Изменить', edit_user_registration_path(current_user), class: 'dropdown-item' %>
                                <%= link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                            </div>
                        <div>
                    <% else %>
                        <div class="nav-item">
                            <%= link_to 'Зарегестрироваться', new_user_registration_path, class: 'nav-link' %>
                        </div>
                        <div class="nav-item">
                            <%= link_to 'Войти', new_user_session_path, class: 'nav-link' %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <%= render 'layouts/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="container justify-content-center">
        <%= yield %>
      </div>
  </body>
</html>

app/views/posts/_form.html.erb
<p id="notice"><%= notice %></p>

<%= form_with model: @post, local: true do |form| %>
<% if @post.errors.any? %>
    <div class="errors">
        Total errors: <%= @post.errors.count %>
        <ul>
            <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>
    <div class="field">
        <%= form.label :Галерея %><br />
        <%= form.file_field :images, multiple:true %>
        <%= form.hidden_field :user_id, value: current_user %>
    </div>
    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/posts/edit.html.erb
<%= render  "form" %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <% if post.images.attached? %>
        <% post.images.each do |image| %>
            <%= link_to post.user.name, user_path(post.user) %><br>
                <%= image_tag image, size: 300 %>
                <% pre_like = post.likes.find { |like| like.user == current_user} %>
                <% if pre_like %>
                    <%= button_to 'Unlike', post_like_path(post, pre_like), method: :delete if user_signed_in?%>
                <% else %>
                    <%= button_to 'Like', post_likes_path(post), method: :post if user_signed_in? %>
                <% end %>
            Like:<%= post.likes.size %><br>
        <% end %>
    <% end %>
<% end %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<h1>Пост
    <%= @post.user.name %><br>
</h1>
<% @post.images.each do |picture| %>
    <%= image_tag picture %>
    <%= link_to 'Удалить фото', delete_image_path(picture.id), method: :delete %><br>
    <%= button_to 'Like', post_likes_path(@post), method: :post  %>
<% end %>

<p><%= @post.likes.count %> </p>
<%= link_to 'Удалить пост', post_url, method: :delete %>

app/views/users/show.html.erb
<% if @user.avatar.attached? %>
    <%= image_tag @user.avatar, size: '200' %>
<% end %>
<h3>
    <strong><%= @user.name %></strong>
</h3>
<% @user.posts.each do |post| %>
    <% if post.images.attached? %>
        <% post.images.each do |image| %>
            <%= image_tag image %>
            <%= link_to 'Удалить фото', delete_image_path(image.id), method: :delete %><br>
        <% end %>
        <%= button_to 'Like', post_likes_path(post), method: :post  %>
        <p><%= post.likes.count %></p>
    <% end %>


<!-- <%= link_to 'Коментарий', '#', id: 'toggle_comments' %> -->
<div id="comments_container">
    <%= render 'comments/form', comment: Comment.new(post_id: post.id) %>
</div>

<% end %>

<% if current_user && current_user == @user %>
    <%= link_to  "Добавить пост", new_post_path %>
<% end %>